spring:
  application:
    name: SpeakSharp
  datasource:
      url: {DB_URL}
      username: ${DB_USER}
      password: ${DB_PASSWORD}
      driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    properties:
      hibernate:
        format_sql: true
telegram:
  bot:
    username: {TG_USERNAME}
    token: {TG_TOKEN}
server:
  port: ${PORT:8080}